package com.github.sgeorgiev24.leaf.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val color_theme_light_primary = Color(0xFF4459A9)
val color_theme_light_onPrimary = Color(0xFFFFFFFF)
val color_theme_light_primaryContainer = Color(0xFFDCE1FF)
val color_theme_light_onPrimaryContainer = Color(0xFF001552)
val color_theme_light_secondary = Color(0xFF0B61A4)
val color_theme_light_onSecondary = Color(0xFFFFFFFF)
val color_theme_light_secondaryContainer = Color(0xFFD2E4FF)
val color_theme_light_onSecondaryContainer = Color(0xFF001C37)
val color_theme_light_tertiary = Color(0xFF855300)
val color_theme_light_onTertiary = Color(0xFFFFFFFF)
val color_theme_light_tertiaryContainer = Color(0xFFFFDDB8)
val color_theme_light_onTertiaryContainer = Color(0xFF2A1700)
val color_theme_light_error = Color(0xFFBA1A1A)
val color_theme_light_errorContainer = Color(0xFFFFDAD6)
val color_theme_light_onError = Color(0xFFFFFFFF)
val color_theme_light_onErrorContainer = Color(0xFF410002)
val color_theme_light_background = Color(0xFFFFFBFF)
val color_theme_light_onBackground = Color(0xFF030865)
val color_theme_light_surface = Color(0xFFFFFBFF)
val color_theme_light_onSurface = Color(0xFF030865)
val color_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val color_theme_light_onSurfaceVariant = Color(0xFF45464F)
val color_theme_light_outline = Color(0xFF767680)
val color_theme_light_inverseOnSurface = Color(0xFFF1EFFF)
val color_theme_light_inverseSurface = Color(0xFF1E2578)
val color_theme_light_inversePrimary = Color(0xFFB7C4FF)
val color_theme_light_shadow = Color(0xFF000000)
val color_theme_light_surfaceTint = Color(0xFF4459A9)
val color_theme_light_outlineVariant = Color(0xFFC6C5D0)
val color_theme_light_scrim = Color(0xFF000000)

val color_theme_dark_primary = Color(0xFFB7C4FF)
val color_theme_dark_onPrimary = Color(0xFF0D2879)
val color_theme_dark_primaryContainer = Color(0xFF2A4190)
val color_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val color_theme_dark_secondary = Color(0xFFA0C9FF)
val color_theme_dark_onSecondary = Color(0xFF00325A)
val color_theme_dark_secondaryContainer = Color(0xFF00497F)
val color_theme_dark_onSecondaryContainer = Color(0xFFD2E4FF)
val color_theme_dark_tertiary = Color(0xFFFFB95F)
val color_theme_dark_onTertiary = Color(0xFF472A00)
val color_theme_dark_tertiaryContainer = Color(0xFF653E00)
val color_theme_dark_onTertiaryContainer = Color(0xFFFFDDB8)
val color_theme_dark_error = Color(0xFFFFB4AB)
val color_theme_dark_errorContainer = Color(0xFF93000A)
val color_theme_dark_onError = Color(0xFF690005)
val color_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val color_theme_dark_background = Color(0xFF030865)
val color_theme_dark_onBackground = Color(0xFFE0E0FF)
val color_theme_dark_surface = Color(0xFF030865)
val color_theme_dark_onSurface = Color(0xFFE0E0FF)
val color_theme_dark_surfaceVariant = Color(0xFF45464F)
val color_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val color_theme_dark_outline = Color(0xFF90909A)
val color_theme_dark_inverseOnSurface = Color(0xFF030865)
val color_theme_dark_inverseSurface = Color(0xFFE0E0FF)
val color_theme_dark_inversePrimary = Color(0xFF4459A9)
val color_theme_dark_shadow = Color(0xFF000000)
val color_theme_dark_surfaceTint = Color(0xFFB7C4FF)
val color_theme_dark_outlineVariant = Color(0xFF45464F)
val color_theme_dark_scrim = Color(0xFF000000)

private val LeafLightColors = lightColorScheme(
    primary = color_theme_light_primary,
    onPrimary = color_theme_light_onPrimary,
    primaryContainer = color_theme_light_primaryContainer,
    onPrimaryContainer = color_theme_light_onPrimaryContainer,
    secondary = color_theme_light_secondary,
    onSecondary = color_theme_light_onSecondary,
    secondaryContainer = color_theme_light_secondaryContainer,
    onSecondaryContainer = color_theme_light_onSecondaryContainer,
    tertiary = color_theme_light_tertiary,
    onTertiary = color_theme_light_onTertiary,
    tertiaryContainer = color_theme_light_tertiaryContainer,
    onTertiaryContainer = color_theme_light_onTertiaryContainer,
    error = color_theme_light_error,
    errorContainer = color_theme_light_errorContainer,
    onError = color_theme_light_onError,
    onErrorContainer = color_theme_light_onErrorContainer,
    background = color_theme_light_background,
    onBackground = color_theme_light_onBackground,
    surface = color_theme_light_surface,
    onSurface = color_theme_light_onSurface,
    surfaceVariant = color_theme_light_surfaceVariant,
    onSurfaceVariant = color_theme_light_onSurfaceVariant,
    outline = color_theme_light_outline,
    inverseOnSurface = color_theme_light_inverseOnSurface,
    inverseSurface = color_theme_light_inverseSurface,
    inversePrimary = color_theme_light_inversePrimary,
    surfaceTint = color_theme_light_surfaceTint,
    outlineVariant = color_theme_light_outlineVariant,
    scrim = color_theme_light_scrim,
)

private val LeafDarkColors = darkColorScheme(
    primary = color_theme_dark_primary,
    onPrimary = color_theme_dark_onPrimary,
    primaryContainer = color_theme_dark_primaryContainer,
    onPrimaryContainer = color_theme_dark_onPrimaryContainer,
    secondary = color_theme_dark_secondary,
    onSecondary = color_theme_dark_onSecondary,
    secondaryContainer = color_theme_dark_secondaryContainer,
    onSecondaryContainer = color_theme_dark_onSecondaryContainer,
    tertiary = color_theme_dark_tertiary,
    onTertiary = color_theme_dark_onTertiary,
    tertiaryContainer = color_theme_dark_tertiaryContainer,
    onTertiaryContainer = color_theme_dark_onTertiaryContainer,
    error = color_theme_dark_error,
    errorContainer = color_theme_dark_errorContainer,
    onError = color_theme_dark_onError,
    onErrorContainer = color_theme_dark_onErrorContainer,
    background = color_theme_dark_background,
    onBackground = color_theme_dark_onBackground,
    surface = color_theme_dark_surface,
    onSurface = color_theme_dark_onSurface,
    surfaceVariant = color_theme_dark_surfaceVariant,
    onSurfaceVariant = color_theme_dark_onSurfaceVariant,
    outline = color_theme_dark_outline,
    inverseOnSurface = color_theme_dark_inverseOnSurface,
    inverseSurface = color_theme_dark_inverseSurface,
    inversePrimary = color_theme_dark_inversePrimary,
    surfaceTint = color_theme_dark_surfaceTint,
    outlineVariant = color_theme_dark_outlineVariant,
    scrim = color_theme_dark_scrim,
)

fun getColors(isLightTheme: Boolean) = if (isLightTheme) LeafLightColors else LeafDarkColors